-- 0010 — THE EVIDENCE A RUN PRESENTED, ON THE RECORD THAT REPORTS IT.
--
-- D-2 said `outcome` is decided by a CONTRACT. What shipped decided it by
-- reading `observed_records.result` — a column the REPORTING agent fills in.
-- A principal holding the §6.2 `report_outcome` grant therefore declared its own
-- success and §4's `outcome` column printed it, which is the exact thing [M-6]
-- forbids: a task that finished is not a task that succeeded, and a task nobody
-- evaluated is not a task that failed.
--
-- The evaluator now executes the manifest's own `check`. A check has to be
-- executed AGAINST something, and that something is the named values a run
-- produced — the `evidence` the signed `outcome_contract` demands. Those values
-- had nowhere to live: `result` was a verdict with no working, so the working
-- is what this migration adds.
--
-- WHY A COLUMN AND NOT A TABLE. Evidence is a property of ONE output record, it
-- is written once with that record and never joined to anything, and a table
-- would add a second INSERT-only journal with its own triggers for a value that
-- has exactly one owner. `result` stays: it is what the reporter CLAIMED, and
-- keeping it is what lets a reader see a claim and its evaluation disagree.
-- Nothing computes `outcome` from it any more.
--
-- NOTHING IS BACK-FILLED. A record written before this migration presents no
-- evidence, so its skill's `outcome` is `unknown` with a reason — never `no`
-- [I-1], [A-0]. That is the same rule `0004` and `0009` were written under.
--
-- The column is NULLable and bounded. It carries a JSON object of named values.
--
-- WHAT THIS COLUMN IS ALLOWED TO HOLD, AND WHERE THAT IS DECIDED. This comment
-- has been wrong four times, in the same direction, and every correction is
-- kept because each one is what made the one before it true.
--
--   IT SAID THE COLUMN "is never a transcript" while `evidenceOf` in
--   `src/service.ts` accepted ANY name of 1 to 80 characters. A reviewer put a
--   secret-shaped NAME and a field called `extra_transcript` through the
--   shipped `/v1/observations` surface and both were stored verbatim.
--
--   THE NAMES WERE THEN CLOSED and the sentence was still wrong, because a
--   closed set of names over an open set of VALUES is a key-value store with a
--   vocabulary. A reviewer stored a secret under the contract's own `stdout`,
--   word for word, and a whole transcript goes the same way under any name at
--   all. A CHECK on length is not a CHECK on subject, and this file asserted
--   the second while enforcing the first.
--
--   THE VALUES WERE THEN CLOSED AND THE SENTENCE WAS STILL WRONG, twice over.
--   The value rule was written RECURSIVELY, so its bound of 32 applied to each
--   LEVEL of a list and therefore to no value: a reviewer put a transcript
--   through the same shipped surface as NESTED ARRAYS OF BYTES under the base
--   name `exit_code`, and read it back out of this column byte for byte. And
--   the rule admitted, as a string, any LITERAL THE SIGNED CHECK NAMED — which
--   made the AUTHOR of a skill, who is a fleet agent like any other, able to
--   sign its own prose into `check.command` and echo it in here.
--
--   AND THEN THE NAME ITSELF, which every correction above was about what a
--   name CARRIES and never about what a name IS. A name the signed contract
--   declares is a string the AUTHOR wrote and it is stored here AS A JSON KEY,
--   word for word; the schema bounded it at 20 names of 80 characters and put
--   no FORM on it at all, so spaces, punctuation, upper case and the whole of
--   unicode were admissible. A contract declaring `the operator pasted the
--   key ` and a credential as NAMES, with a run of its own presenting them,
--   went through the same shipped surface and the material came back out of
--   this column byte for byte.
--
-- SO ALL THREE CHANNELS ARE CLOSED, AND NONE OF THEM IS CLOSED IN SQL.
--
--   NAMES, WHICH SET: `EVIDENCE_NAMES` (`src/outcome.ts`, derived from the
--   check table) plus the names the SIGNED `outcome_contract.evidence` of the
--   version a record's marker identifies declares.
--
--   NAMES, WHICH FORM: an IDENTIFIER — a lowercase letter, then lowercase
--   letters, digits and underscores, at most 40 characters. `EVIDENCE_NAME`
--   (`src/outcome.ts`) is the rule and the schema carries the same pattern, so
--   a contract that names a sentence cannot be PACKED, and `outcomeContractOf`
--   (`src/manifest.ts`) refuses one that reaches the report path by any other
--   route — the names then fall back to the derived set and that contract
--   declares nothing. A name is NOT stored as a digest, deliberately: a reader
--   of this journal has to see WHICH quantity a run presented, and a column of
--   digests would record evidence while showing nobody what kind. What the form
--   takes away is text — there is no space, no punctuation, no case and no
--   unicode in that alphabet, so prose and a pasted credential are outside it.
--   What it leaves, and this is stated rather than glossed: a name is still a
--   string an author CHOSE, and an identifier alphabet can be made to carry an
--   encoding, exactly as the flat list of integers a value may be can. No text
--   arrives here as itself; that is the property, and it is the whole of it.
--
--   VALUES: a boolean, a safe integer or a digest of the form
--   `sha256:<64 lowercase hex>` — or a FLAT list of at most 32 of those, with
--   NO NESTING at any depth, so the bound counts the whole value and not one
--   level of it. The rule is `isAdmissibleEvidenceValue` (`src/outcome.ts`),
--   in one place, so the boundary that refuses a report and the checks that
--   read a value cannot disagree about what a value is.
--
--   AND WHERE A SIGNED `check` NAMES A `command` OR AN `artifact_path`, a run
--   presents THE DIGEST of it: the registry compares that against the digest
--   it computes from the signed parameter itself, so the check decides exactly
--   what it decided before and no string an author wrote is a value. There is
--   no enumeration of admissible strings any more — a permitting set nobody
--   consults is a hole that has merely not been walked through yet.
--
-- Where no contract can be read — an unknown marker, a manifest that no longer
-- hashes to what was signed, a contract whose declared names are not
-- identifiers — the names are the derived list and nothing else: the boundary
-- fails closed on every channel.
--
-- SQLite cannot express any of these rules, so this comment does not claim
-- SQLite does. What the constraint below enforces is a bound on SIZE, which is
-- what a bound on size is. Each rule is enforced in one function, and a probe
-- reads THIS TABLE after a refused report — decoding the numbers it holds, not
-- only searching it for letters, and reading the KEYS as well as the values —
-- to show nothing of the attack was written.
--
-- SO THE TEXT OF A RECORD DOES NOT REACH THIS SCHEMA, AND HERE IS WHY IT
-- CANNOT. Not because a field is named `evidence` rather than `transcript`, and
-- not because anybody promised: because a value that is free text is refused at
-- the boundary under EVERY name, the contract's own included; because a value
-- may not be a tree, so text cannot arrive spread across one; and because the
-- author's own strings are compared as digests rather than carried. Text is a
-- transcript however the field is called and however it is broken up. [I-7]'s
-- other half is untouched and always was: a record's text is reduced to §5
-- markers at the boundary and no column of this schema stores it.
--
-- AND WHAT AN AUTHOR SIGNS DOES NOT REACH IT EITHER, which used to be the
-- exception this paragraph had to make. A REPORTER's text is refused as a
-- value; an AUTHOR's text is refused as a name, because a name is an identifier
-- and a sentence is not one. Both are agents of the same fleet, so the
-- distinction was one of route and not of trust — and the route is now shut at
-- both ends, which is why this file no longer has an exception to declare.

ALTER TABLE observed_records ADD COLUMN evidence TEXT
  CHECK(evidence IS NULL OR (length(evidence) BETWEEN 2 AND 4000));
