#!/usr/bin/env node
// Regenerates src/unicode-tables.ts — the committed Unicode data the archive
// profile runs on (§4.1b, point 2).
//
// Everything the profile needs from Unicode lives here: case folding for the
// collision rule, and canonical decomposition / combining classes / composition
// pairs for the NFC rule. Both must come from committed data, because every
// runtime ships its own ICU and they disagree — Node 22 carries Unicode 17,
// Bun 1.3 carries 15.1, and the same package would otherwise verify differently
// depending on where the verifier runs.
//
// Code points outside this repertoire are NOT rejected: with no decomposition
// and no fold recorded, they pass both rules through unchanged.
//
// Run: node --experimental-strip-types tools/gen-unicode-tables.ts
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const raw = execFileSync("python3", [
  "-c",
  `import json,sys,unicodedata
folds={}; decomp={}; ccc={}
for cp in range(0x110000):
    ch=chr(cp)
    f=ch.casefold()
    if f!=ch: folds[cp]=f
    d=unicodedata.decomposition(ch)
    if d and not d.startswith('<'):
        decomp[cp]=[int(x,16) for x in d.split()]
    c=unicodedata.combining(ch)
    if c: ccc[cp]=c
sys.stdout.write(json.dumps({
  "unicode": unicodedata.unidata_version,
  "folds": folds, "decomp": decomp, "ccc": ccc,
}))`,
], { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });

const data = JSON.parse(raw) as {
  unicode: string;
  folds: Record<string, string>;
  decomp: Record<string, number[]>;
  ccc: Record<string, number>;
};

// Composition pairs: a canonical decomposition of exactly two code points
// composes back, unless the character is composition-excluded. Exclusions are
// derived rather than listed: a pair has a non-starter decomposition when the
// composed character or its first component is a non-starter (ccc ≠ 0); the
// listed composition exclusions fall out of the Python NFC round-trip below.
const pairs: Array<[number, number, number]> = [];
for (const [cpStr, seq] of Object.entries(data.decomp)) {
  if (seq.length !== 2) continue;
  const cp = Number(cpStr);
  const [a, b] = seq as [number, number];
  if (data.ccc[String(a)]) continue; // first component is a non-starter
  if (data.ccc[String(cp)]) continue; // decomposes to a non-starter
  pairs.push([a, b, cp]);
}
// Verify each derived pair against Python's own NFC, dropping the excluded ones.
const verified = JSON.parse(
  execFileSync("python3", [
    "-c",
    `import json,sys,unicodedata
pairs=json.load(sys.stdin)
out=[p for p in pairs if unicodedata.normalize('NFC', chr(p[0])+chr(p[1]))==chr(p[2])]
sys.stdout.write(json.dumps(out))`,
  ], { input: JSON.stringify(pairs), encoding: "utf8", maxBuffer: 64 * 1024 * 1024 }),
) as Array<[number, number, number]>;

const hex = (n: number) => `0x${n.toString(16).toUpperCase()}`;
const out: string[] = [
  "// GENERATED by tools/gen-unicode-tables.ts — do not edit by hand.",
  "//",
  `// Unicode ${data.unicode}, pinned per §4.1b, point 2. The archive profile`,
  "// evaluates the NFC rule and the case-collision rule against these tables and",
  "// never against the host runtime's, so one package gets one verdict on every",
  "// runtime. Code points outside this repertoire are not rejected — with no",
  "// decomposition and no fold recorded they pass both rules through unchanged.",
  "//",
  "// CASE_FOLD: Unicode default full case folding, direction as Unicode defines",
  "// it (Cherokee folds lowercase to UPPERCASE). Turkic-only mappings excluded.",
  `export const UNICODE_VERSION = ${JSON.stringify(data.unicode)};`,
  "",
  "export const CASE_FOLD: ReadonlyMap<number, string> = new Map([",
  ...Object.entries(data.folds)
    .map(([cp, f]) => [Number(cp), f] as const)
    .sort((a, b) => a[0] - b[0])
    .map(([cp, f]) => `  [${hex(cp)}, ${JSON.stringify(f)}],`),
  "]);",
  "",
  "/** Canonical decomposition (single step; apply recursively). */",
  "export const DECOMP: ReadonlyMap<number, readonly number[]> = new Map([",
  ...Object.entries(data.decomp)
    .map(([cp, seq]) => [Number(cp), seq] as const)
    .sort((a, b) => a[0] - b[0])
    .map(([cp, seq]) => `  [${hex(cp)}, [${seq.map(hex).join(", ")}]],`),
  "]);",
  "",
  "/** Canonical combining class; absent means 0 (a starter). */",
  "export const CCC: ReadonlyMap<number, number> = new Map([",
  ...Object.entries(data.ccc)
    .map(([cp, c]) => [Number(cp), c] as const)
    .sort((a, b) => a[0] - b[0])
    .map(([cp, c]) => `  [${hex(cp)}, ${c}],`),
  "]);",
  "",
  "/** Primary composition: \"starter,combining\" → composed code point. */",
  "export const COMPOSE: ReadonlyMap<string, number> = new Map([",
  ...verified
    .sort((x, y) => x[0] - y[0] || x[1] - y[1])
    .map(([a, b, cp]) => `  ["${a},${b}", ${hex(cp)}],`),
  "]);",
  "",
];
writeFileSync(join(root, "src", "unicode-tables.ts"), out.join("\n"));
console.log(
  `src/unicode-tables.ts written (Unicode ${data.unicode}): ` +
    `${Object.keys(data.folds).length} folds, ${Object.keys(data.decomp).length} decompositions, ` +
    `${Object.keys(data.ccc).length} combining classes, ${verified.length} composition pairs`,
);
